# These values can be used to customize the bitnami mysql helm chart.
# https://github.com/bitnami/charts/tree/main/bitnami/mysql

architecture: standalone

auth:
  rootPassword: insecureRootPassword
  username: example-user
  password: example-pass
  createDatabase: true
  database: "PHAROS"

primary:
  extraVolumeMounts:
    - name: pharos-nfs
      mountPath: /Data_services_storage
  extraVolumes:
    - name: pharos-nfs
      nfs:
        server: na-projects.edc.renci.org
        path: /stars/Data_services
  resources:
    limits:
      cpu: 2
      memory: 16Gi
    requests:
      cpu: 1
      memory: 12Gi
  persistence:
    size: 100Gi

# this might work
# networkPolicy:
#   explicitNamespacesSelector:
#     matchLabels:
#       kubernetes.io/metadata.name: data-services


# image:
#  debug: true