# Values for running data-services on Sterling at RENCI

replicaCount: 1

dataServices:
  graphID: "all"
  # optionally use a remote graph spec by supplying a url
  # graphSpec: 'https://stars.renci.org/var/data_services/graph_specs/current-graph-spec.yml'
  graphSpec: 'default-graph-spec.yml'
  # useLocalGraphSpec true if the graphSpec is a file in the codebase (mainly for testing), false if a remote URL
  useLocalGraphSpec: true
  buildMode: true
  image:
    repository: ghcr.io/robokopu24/orion
    pullPolicy: IfNotPresent
    tag: v1.0.7
  graphsVolume:
    use_nfs: true
    nfs_server: na-projects.edc.renci.org
    nfs_path: /stars/Data_services
    nfs_mount_subpath: biolink3/graphs/
  sourcesVolume:
    use_nfs: true
    nfs_server: na-projects.edc.renci.org
    nfs_path: /stars/Data_services
    nfs_mount_subpath: biolink3/storage/
  extraVolume:
    use_extra_volume: true
    nfs_server: na-projects.edc.renci.org
    nfs_path: /stars/Data_services
    nfs_mount_subpath: sterling/
  neo4jScratchVolume:
    size: 80Gi
  resources:
    limits:
      cpu: "2500m"
      memory: 40Gi
      ephemeral-storage: 2Gi
    requests:
      cpu: "2500m"
      memory: 32Gi
      ephemeral-storage: 1Gi
  httpsProxy:
    useProxy: true
    proxyURL: http://proxy.renci.org:8080/
  securityContext:
    runAsUser: 30000
    runAsGroup: 1000
  normalization:
    nodeNormEndpoint: https://nodenormalization-sri.renci.org/
    edgeNormEndpoint: https://bl-lookup-sri.renci.org/
  outputURL: https://stars.renci.org/var/plater/bl-3.2.1/

pharos:
  host: pod-host-or-ip
  port: 3306
  user: ds-user
  password: ds-pass
  db_name: PHAROS

drugcentral:
  host: pod-host-or-ip
  port: 5432
  user: dc-user
  password: dc-pass
  db_name: drugcentral

